[project]
name = "ysshd"
version = "0.1.0"
description = "yet another ssh daemon"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
ysshd = "ysshd:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
